import type {Metadata} from "next";
import {Inter, Sora} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import {ReactNode} from "react";
import Footer from "@/components/Footer";
import {client} from "@/utils/sanity";
import {ProductPage} from "@/types";
import StoreProvider from "@/redux/StoreProvider";
import {Toaster} from "@/components/ui/toaster";
import ReduxInitializer from "@/redux/ReduxInitializer";

const inter = Inter({subsets: ["latin"]});
const sora = Sora({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Dine Market",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: ReactNode;
}>) {

    async function getProductPages() {
        const CONTENT_QUERY = `
            *[_type == "productPage"] | order(_createdAt asc) {
              _id,
              title,
              slug,
              _createdAt
            }
          `;
        return await client.fetch(CONTENT_QUERY)
    }

    const productPages: ProductPage[] = await getProductPages();


    return (
        <StoreProvider>
            <ReduxInitializer>
                <html lang="en">
                <body className={sora.className + " bg-[#fcfcfc]"}>
                <Navbar productPages={productPages}/>
                {children}
                <Toaster/>
                <Footer/>
                </body>
                </html>
            </ReduxInitializer>
        </StoreProvider>
    );
}
